/**
 * 3-dimensional triangulation: 3-sphere (simplex boundary)
 * Code automatically generated by dumpConstruction().
 */

/**
 * The following arrays describe the gluings between simplices.
 */

const int adjacencies[5][4] = {
    { 1, 2, 3, 4},
    { 0, 2, 3, 4},
    { 0, 1, 3, 4},
    { 0, 1, 2, 4},
    { 0, 1, 2, 3}
};

const int gluings[5][4][4] = {
    { { 0, 1, 2, 3 }, { 1, 0, 2, 3 }, { 1, 2, 0, 3 }, { 1, 2, 3, 0 } },
    { { 0, 1, 2, 3 }, { 0, 1, 2, 3 }, { 0, 2, 1, 3 }, { 0, 2, 3, 1 } },
    { { 1, 0, 2, 3 }, { 0, 1, 2, 3 }, { 0, 1, 2, 3 }, { 0, 1, 3, 2 } },
    { { 2, 0, 1, 3 }, { 0, 2, 1, 3 }, { 0, 1, 2, 3 }, { 0, 1, 2, 3 } },
    { { 3, 0, 1, 2 }, { 0, 3, 1, 2 }, { 0, 1, 3, 2 }, { 0, 1, 2, 3 } }
};

/**
 * The following code constructs a 3-dimensional triangulation
 * based on the information stored in the arrays above.
 */

Triangulation<3> tri;
tri.insertConstruction(5, adjacencies, gluings);

